"""empty message

Revision ID: 589ebdeebbca
Revises: 
Create Date: 2023-07-14 08:46:11.096138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589ebdeebbca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_news_name'), ['name'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_id', sa.String(length=26), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_pages_name'), ['name'])
        batch_op.create_foreign_key(batch_op.f('fk_pages_study_id_studies'), 'studies', ['study_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_studies_name'), ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_name'), type_='unique')

    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_studies_name'), type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pages_study_id_studies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_pages_name'), type_='unique')
        batch_op.drop_column('study_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_news_name'), type_='unique')

    # ### end Alembic commands ###
